# Generated by Django 3.0.5 on 2020-04-29 12:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('market', 'Market Risk'), ('credit', 'Credit Risk'), ('liquidity', 'Liquidity Risk'), ('pricing', 'Pricing Risk'), ('compliance', 'Compliance Risk')], max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.Report')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
