# Generated by Django 3.0.5 on 2020-05-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_app', '0002_auto_20200509_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiskAssessment',
            new_name='Risk',
        ),
        migrations.AddField(
            model_name='report',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='validator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='validator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssignedUser',
        ),
    ]
