# Generated by Django 3.0.5 on 2020-05-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_auto_20200523_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='report_app.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='report_app.Report'),
        ),
    ]
