# Generated by Django 3.0.5 on 2020-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0005_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_name',
            field=models.CharField(choices=[('create', 'Create'), ('validate', 'Validate'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20),
        ),
    ]
